;
; Netatalk 4.x configuration file
;
[Global]
server name = throwback
appletalk = yes
uam list = uams_randnum.so uams_guest.so
afp interfaces = ens160
ddp zone = netjibbing
guest account = ubuntu
log level = default:debug

[JonesFarm]
path = /mnt/hgfs/MacPro
cnid scheme = sqlite
guest ok = yes
read only = no
unix priv = yes
ea = ad
invisible dots = yes
veto files = /.DS_Store/.TemporaryItems/.Trashes/.fseventsd/

[Drop Box]
path = /mnt/hgfs/MacPro/Drop Files Here
cnid scheme = sqlite
guest ok = yes
read only = no
unix priv = no
ea = none
invisible dots = yes
veto files = /.DS_Store/.TemporaryItems/.Trashes/.fseventsd/
